[session_icons]

Dotfiles        = "ğŸ¶"
Neovim          = "ğŸ¡"
Hammerspoon     = "ğŸš"
Tmux            = "ğŸ "

Tav             = "ğŸ¦Š"
Ap              = "ğŸ¦š"

ECS             = "ğŸ„"

Play            = "ğŸ­"
Swift           = "ğŸ­"
Rust            = "ğŸ­"

Jack            = "ğŸ¦œ"
