[session_icons]

Dotfiles        = " "
Neovim          = " "
Hammerspoon     = " "
Tmux            = " "

Tav             = " "
Ap              = " "

ECS             = " "

Play            = " "
Swift           = " "
Rust            = " "
